name: snow_droughts
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affine=2.3.1
  - aiohttp=3.8.3
  - aiosignal=1.3.1
  - alsa-lib=1.2.7.2
  - appdirs=1.4.4
  - asciitree=0.3.3
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - attr=2.5.1
  - attrs=22.1.0
  - backcall=0.2.0
  - blinker=1.5
  - blosc=1.21.1
  - bokeh=2.4.3
  - boost-cpp=1.78.0
  - branca=0.5.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cachetools=5.2.0
  - cairo=1.16.0
  - cartopy=0.21.0
  - cdat_info=8.2.1
  - cdms2=3.1.5
  - cdtime=3.1.4
  - cdutil=8.2.1
  - certifi=2022.12.7
  - cf_xarray=0.7.4
  - cffi=1.15.1
  - cfitsio=4.1.0
  - cftime=1.6.2
  - charset-normalizer=2.1.1
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.2.0
  - colorama=0.4.6
  - colorcet=3.0.0
  - contourpy=1.0.5
  - cryptography=37.0.4
  - curl=7.85.0
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2022.12.1
  - dask-core=2022.12.1
  - dbus=1.13.6
  - debugpy=1.5.1
  - decorator=5.1.1
  - distarray=2.12.2
  - distributed=2022.12.1
  - entrypoints=0.4
  - esmf=8.2.0
  - esmpy=8.2.0
  - executing=0.8.3
  - expat=2.4.9
  - fasteners=0.17.3
  - fastprogress=1.0.3
  - fftw=3.3.10
  - fiona=1.8.21
  - folium=0.12.1.post1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.37.4
  - freeglut=3.2.2
  - freetype=2.12.1
  - freexl=1.0.6
  - frozenlist=1.3.3
  - fsspec=2022.11.0
  - future=0.18.2
  - g2clib=1.6.3
  - gcsfs=2022.11.0
  - gdal=3.5.2
  - genutil=8.2.1
  - geopandas=0.11.1
  - geopandas-base=0.11.1
  - geos=3.11.0
  - geotiff=1.7.1
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.74.0
  - glib-tools=2.74.0
  - google-api-core=2.10.1
  - google-auth=2.15.0
  - google-auth-oauthlib=0.8.0
  - google-cloud-core=2.3.2
  - google-cloud-storage=2.7.0
  - google-crc32c=1.1.2
  - google-resumable-media=2.4.0
  - googleapis-common-protos=1.57.0
  - grpc-cpp=1.47.1
  - grpcio=1.47.1
  - gst-plugins-base=1.20.3
  - gstreamer=1.20.3
  - hdf4=4.2.15
  - hdf5=1.12.2
  - heapdict=1.0.1
  - icu=70.1
  - idna=3.4
  - importlib-metadata=4.11.4
  - importlib_resources=5.9.0
  - intake=0.6.6
  - intake-esm=2022.9.18
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=8.4.0
  - jack=1.9.18
  - jasper=2.0.33
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json-c=0.16
  - jsonschema=4.16.0
  - jupyter_client=7.3.5
  - jupyter_core=4.10.0
  - kealib=1.4.15
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lazy-object-proxy=1.7.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=4.0.0
  - libabseil=20220623.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.65
  - libcblas=3.9.0
  - libcdms=3.1.2
  - libcf=1.0.3
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=7.85.0
  - libdap4=3.20.6
  - libdb=6.2.32
  - libdeflate=1.14
  - libdrs=3.1.2
  - libdrs_f=3.1.2
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.3.4
  - libgcc-ng=12.1.0
  - libgdal=3.5.2
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.74.0
  - libglu=9.0.0
  - libiconv=1.17
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libllvm14=14.0.6
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.38
  - libpq=14.5
  - libprotobuf=3.20.1
  - librttopo=1.1.0
  - libsndfile=1.0.31
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.39.4
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libtool=2.4.6
  - libudev1=249
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.10.2
  - libzip=1.9.2
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - llvmlite=0.39.1
  - locket=1.0.0
  - lz4=4.0.2
  - lz4-c=1.9.3
  - mapclassify=2.4.3
  - markupsafe=2.1.1
  - matplotlib=3.6.0
  - matplotlib-base=3.6.0
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - msgpack-python=1.0.4
  - multidict=6.0.2
  - munch=2.5.0
  - munkres=1.1.4
  - mysql-common=8.0.30
  - mysql-libs=8.0.30
  - nbformat=5.6.1
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - netcdf-fortran=4.6.0
  - netcdf4=1.6.1
  - networkx=2.8.7
  - nspr=4.32
  - nss=3.78
  - numba=0.56.3
  - numcodecs=0.11.0
  - numpy=1.22.3
  - oauthlib=3.2.2
  - openblas=0.3.21
  - openjpeg=2.5.0
  - openssl=1.1.1s
  - packaging=21.3
  - pandas=1.5.0
  - param=1.12.0
  - parso=0.8.3
  - partd=1.3.0
  - patsy=0.5.3
  - pcre=8.45
  - pcre2=10.37
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - ply=3.11
  - poppler=22.04.0
  - poppler-data=0.4.11
  - portaudio=19.6.0
  - postgresql=14.5
  - proj=9.0.1
  - prompt-toolkit=3.0.20
  - protobuf=3.20.1
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=14.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pyct=0.4.8
  - pydantic=1.10.2
  - pygments=2.11.2
  - pyjwt=2.6.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyproj=3.4.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.1
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.10.6
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.10
  - pytz=2022.4
  - pyu2f=0.1.5
  - pyzmq=23.2.0
  - qt-main=5.15.6
  - rasterio=1.3.2
  - re2=2022.06.01
  - readline=8.1.2
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rioxarray=0.12.2
  - rsa=4.9
  - rtree=1.0.0
  - scikit-learn=1.1.2
  - scipy=1.9.1
  - seaborn=0.12.1
  - seaborn-base=0.12.1
  - setuptools=63.4.1
  - shapely=1.8.4
  - sip=6.6.2
  - six=1.16.0
  - snappy=1.1.9
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - sparse=0.13.0
  - sqlite=3.39.3
  - stack_data=0.2.0
  - statsmodels=0.13.5
  - tblib=1.7.0
  - threadpoolctl=3.1.0
  - tiledb=2.11.3
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.1.1
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzcode=2022d
  - tzdata=2022c
  - udunits2=2.2.28
  - unicodedata2=14.0.0
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xarray=2022.9.0
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xerces-c=3.2.3
  - xesmf=0.6.3
  - xmip
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2022.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.8.1
  - zarr=2.13.3
  - zeromq=4.3.4
  - zict=2.2.0
  - zipp=3.8.1
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - cmcrameri==1.4
    - pyyaml==6.0
    - scienceplots==2.0.0